# For more information as to what each key-value pair does, got to: https://github.com/alshedivat/al-folio/blob/master/_config.yml

# Site settings
title: Software and Systems Laboratory
first_name: SSL
middle_name:
last_name: Software and Systems Laboratory
email: ssl@cs.luc.edu
description: >
  The official Loyola University Chicago Software and Systems Laboratory website.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
url: # TODO: Change this to the CNAME domain
baseurl: # TODO: Change this to the base directory of the website
last_updated: false
impressum_path:  # Impressum link located in the footer

# Layout settings
navbar_fixed: true
footer_fixed: true

## Dimension settings
max_width: 800px

# Open Graph Settings
serve_og_meta: false
og_image: # Site-wide default Open Graph preview image

# Socials
github_username: SoftwareSystemsLaboratory
# twitter_username: # your Twitter handle
# linkedin_username: # your LinkedIn user name
# scholar_userid: # your Google Scholar ID
# orcid_id: # your ORCID ID
# medium_username: # your Medium username
# quora_username: # your Quora username
# publons_id: # your ID on Publons
# research_gate_profile: # your profile on ResearchGate
# blogger_url: # your blogger URL
work_url: https://www.luc.edu/cs/
# keybase_username: # your keybase user name
# wikidata_id: # your wikidata id

contact_note: >
  Contact Email: <a href="mailto:ssl@cs.luc.edu">ssl@cs.luc.edu</a>

# google_analytics: UA-XXXXXXXXX # TODO: Add Google Analytics
# panelbear_analytics: XXXXXXXXX # TODO: Look into PanelBear

# Blog Settings

blog_name: Software and Systems Laboratory
blog_description: A Loyola University Chicago Computer Science Research Laboratory
permalink: /blog/:year/:title/

## Pagination
pagination:
  enabled: true

# Collections
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# Jekyll settings

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-twitter-plugin
  - jemoji

# Jekyll Scholar

scholar:

  last_name: Einstein
  first_name: [Albert, A.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# Optional Features

enable_google_analytics:    false
enable_panelbear_analytics: false
enable_mansory:             true
enable_math:                true
enable_tooltips:            true
enable_darkmode:            false
show_social_icons:          true

# Library versions

academicons:
  version: "1.9.0"
  integrity: "sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg=="
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.1.2"
mansory:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
